// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mig_headingsttusadd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_headingsttusadd));
        
        string IMigrationMetadata.Id
        {
            get { return "202106021315134_mig_headingsttusadd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
